[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
dice_game = "6TMNF6Wrw7PCBbRgJUJSzQBn8g43XZ4Y28pSFGRX5jER"
vault_betting = "8AUxvDBey9utjsGvtnaAjFeX33SBtMbzeuQPad3BGYAK"

[programs.localnet]
dice_game = "6TMNF6Wrw7PCBbRgJUJSzQBn8g43XZ4Y28pSFGRX5jER"
vault_betting = "8AUxvDBey9utjsGvtnaAjFeX33SBtMbzeuQPad3BGYAK"

[programs.mainnet]
dice_game = "6TMNF6Wrw7PCBbRgJUJSzQBn8g43XZ4Y28pSFGRX5jER"
vault_betting = "8AUxvDBey9utjsGvtnaAjFeX33SBtMbzeuQPad3BGYAK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["contracts/programs/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
